# Site settings
title: Joao Veneroso
description: "A blog for me."
url: "http://www.joaoveneroso.com"
ogimage: "img/default-ogimage.png"
author:
  name: "Joao Veneroso"
  email: "jmfveneroso@gmail.com"
  url: "https://www.joaoveneroso.com"


# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

exclude:
  - drafts
  - upload.sh
